// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace UrbaPark.Infraestructura.AccesoDatos;

public partial class bitacoras_tecnicas
{
    public int id_bitacora { get; set; }

    public int id_informe { get; set; }

    public int id_tecnico { get; set; }

    public DateTime? fecha_registro { get; set; }

    public string actividad_realizada { get; set; }

    public string observaciones { get; set; }

    public string evidencia_url { get; set; }

    public virtual informes_software id_informeNavigation { get; set; }

    public virtual tecnicos_software id_tecnicoNavigation { get; set; }
}