// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace UrbaPark.Infraestructura.AccesoDatos;

public partial class evidencias_informe
{
    public int id_evidencia { get; set; }

    public int id_informe { get; set; }

    public string tipo { get; set; }

    public string ruta_archivo { get; set; }

    public DateTime? fecha_subida { get; set; }

    public virtual informes_software id_informeNavigation { get; set; }
}