// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace UrbaPark.Infraestructura.AccesoDatos;

public partial class incidencias_software
{
   
    public int id_incidencia { get; set; }

    public int id_informe { get; set; }

    public string codigo { get; set; }

    public string descripcion { get; set; }

    public string severidad { get; set; }

    public virtual informes_software id_informeNavigation { get; set; }

    public virtual ICollection<soluciones_aplicadas> soluciones_aplicadas { get; set; } = new List<soluciones_aplicadas>();
}