// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace UrbaPark.Infraestructura.AccesoDatos;

public partial class informes_software
{
    public int id_informe { get; set; }

    public int id_software { get; set; }

    public int id_tecnico { get; set; }

    public DateOnly fecha { get; set; }

    public string tipo { get; set; }

    public string modulo_afectado { get; set; }

    public string descripcion { get; set; }

    public virtual software_parqueaderos id_softwareNavigation { get; set; }

    public virtual tecnicos_software id_tecnicoNavigation { get; set; }

    public virtual ICollection<incidencias_software> incidencias_software { get; set; } = new List<incidencias_software>();
}