// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace UrbaPark.Infraestructura.AccesoDatos;

public partial class parqueaderos
{
    public int id_parqueadero { get; set; }

    public string nombre { get; set; }

    public string direccion { get; set; }

    public int? capacidad { get; set; }

    public string estado { get; set; }

    public virtual ICollection<cronogramas_soporte> cronogramas_soporte { get; set; } = new List<cronogramas_soporte>();

    public virtual ICollection<software_parqueaderos> software_parqueaderos { get; set; } = new List<software_parqueaderos>();
}