// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace UrbaPark.Infraestructura.AccesoDatos;

public partial class rel_cronogramas_tecnicos
{
    public int id_cronograma { get; set; }

    public int id_tecnico { get; set; }

    public bool? asignado { get; set; }

    public bool? confirmado { get; set; }

    public virtual cronogramas_soporte id_cronogramaNavigation { get; set; }

    public virtual tecnicos_software id_tecnicoNavigation { get; set; }
}