// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace UrbaPark.Infraestructura.AccesoDatos;

public partial class software_parqueaderos
{
    public int id_software { get; set; }

    public int id_parqueadero { get; set; }

    public string nombre { get; set; }

    public string version { get; set; }

    public string descripcion { get; set; }

    public virtual parqueaderos id_parqueaderoNavigation { get; set; }

    public virtual ICollection<informes_software> informes_software { get; set; } = new List<informes_software>();
}