// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace UrbaPark.Infraestructura.AccesoDatos;

public partial class tecnicos_software
{
    public int id_tecnico { get; set; }

    public int? id_usuario { get; set; }

    public string nombre { get; set; }

    public string especialidad { get; set; }

    public string telefono { get; set; }

    public string correo_electronico { get; set; }

    public virtual usuarios id_usuarioNavigation { get; set; }

    public virtual ICollection<informes_software> informes_software { get; set; } = new List<informes_software>();

    public virtual ICollection<rel_cronogramas_tecnicos> rel_cronogramas_tecnicos { get; set; } = new List<rel_cronogramas_tecnicos>();
}