// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace UrbaPark.Infraestructura.AccesoDatos;

public partial class usuarios
{
    public int id_usuario { get; set; }

    public string nombre { get; set; }

    public string usuario { get; set; }

    public string contrasena { get; set; }

    public string correo_electronico { get; set; }

    public string estado { get; set; }

    public virtual tecnicos_software tecnicos_software { get; set; }

    public virtual ICollection<roles> id_rol { get; set; } = new List<roles>();
}